# Generated by Django 3.1.4 on 2020-12-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201204_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal', models.PositiveSmallIntegerField()),
                ('progress', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
