# Generated by Django 3.2 on 2021-05-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='title',
        ),
        migrations.AddField(
            model_name='objective',
            name='best_streak',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='current_streak',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='name',
            field=models.CharField(default='aaaaa', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=6),
        ),
        migrations.AddField(
            model_name='objectiveentry',
            name='objective_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.objective'),
        ),
        migrations.AddField(
            model_name='objective',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
