# Generated by Django 3.2 on 2021-05-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210523_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='category_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
