# Generated by Django 3.2 on 2021-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_objective_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiveentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
