# Generated by Django 3.2 on 2021-07-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_objectiveentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='status',
        ),
        migrations.AddField(
            model_name='objective',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
