# Generated by Django 3.2.5 on 2021-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210712_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='best_streak',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='current_streak',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
