# Generated by Django 3.2.5 on 2021-07-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210726_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
            ],
        ),
    ]
