# Generated by Django 3.2.5 on 2021-08-28 19:23

import core.models.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.CharField(default='default', max_length=32, validators=[core.models.settings.validate_color]),
        ),
    ]
