# Generated by Django 3.2.5 on 2021-08-29 21:12

import core.models.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_settings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_view',
            field=models.CharField(default='objectives', max_length=32, validators=[core.models.settings.validate_color]),
        ),
    ]
